# Generated by Django 3.2.4 on 2021-06-19 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='amount',
            field=models.IntegerField(default=1),
        ),
    ]
